[package]
# The URL to the zip package containing all the new files.
url = "http://local.vg:8080/2.0.0/package.zip"
# A hash of the zip package, used to verify it downloaded properly.
hash = "98FE972A3F9B84D336F6DA80FE9712D0073CC6E274E54F4AED3229E8FC1FCFB0"
# All the files in the zip so we make sure they make it to their destination.
files = [
"brightmaps.pk3",
"doom.wad",
"gzdoom-Andrew.ini",
"gzdoom.exe",
"gzdoom.pk3",
"libfluidsynth64.dll",
"libmpg123-0.dll",
"libsndfile-1.dll",
"licenses.zip",
"lights.pk3",
"openal32.dll",
"test dir\\no.txt",
"test dir\\what\\noway.txt",
"zd_extra.pk3"
]


[installer]
# The URL of the actual full installer.
url = "https://releases.rainway.com/Installer_1.0.17.0.exe"
# The hash of the installer to verify it downloaded properly.
hash = "DFF3CCB82433E7C0DD917670062BCC20061F03ECCDDE87C7CB9DC4C2CC117586"