[package]
zip = "https://releases.rainway.com/2.0.0/package.zip" # The URL to the zip package containing all the new files.
hash = "SHA256" # A hash of the zip package, used to verify it downloaded properly.

[installer]
url = "https://releases.rainway.com/2.0.0/installer.exe" # The URL of the actual full installer.
hash = "SHA256" # The hash of the installer to verify it downloaded properly.