name: Rust

on: [push]

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: RustUp
        run: rustup target add i686-pc-windows-msvc
      - name: Build
        run: cargo build --target=i686-pc-windows-msvc --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - run: if exist bootstrapper_release RMDIR bootstrapper_release /S /Q
      - run: MKDIR bootstrapper_release
      - run: DIR
      - run: COPY target\i686-pc-windows-msvc\release\bootstrapper.exe bootstrapper_release\bootstrapper.exe
      - run: COPY target\i686-pc-windows-msvc\release\cli.exe bootstrapper_release\cli.exe
      - run: |
          $test = (Get-Command bootstrapper_release\bootstrapper.exe).Version
          Write-Host $test
        shell: pwsh
      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: bootstrapper_release/

  debug:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: RustUp
        run: rustup target add i686-pc-windows-msvc
      - name: Build
        run: cargo build --target=i686-pc-windows-msvc --verbose
      - name: Run tests
        run: cargo test --verbose
      - run: if exist bootstrapper_debug RMDIR bootstrapper_debug /S /Q
      - run: MKDIR bootstrapper_debug
      - run: DIR
      - run: COPY target\i686-pc-windows-msvc\debug\bootstrapper.exe bootstrapper_debug\bootstrapper.exe
      - run: COPY target\i686-pc-windows-msvc\debug\bootstrapper.exe bootstrapper_debug\cli.exe
      - run: |
          $test = (Get-Command bootstrapper_debug\bootstrapper.exe).Version
          Write-Host $test
        shell: pwsh
      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: bootstrapper_debug/